export const GET_POSTS = 'GET_POSTS';
export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_FAILED = 'POSTS_FAILED';
export const GET_SINGLE_POST = 'GET_SINGLE_POST';
export const LOADED_SINGLE_POST = 'LOADED_SINGLE_POST';
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL';

